name: calculator
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_math: ^0.3.0-nullsafety.1
  math_expressions: ^2.6.0
  get: ^4.7.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.11.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/splash image.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/splash image.png
