name: calculator
description: "A new Flutter project."

publish_to: 'none' 

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_math: ^0.3.0-nullsafety.1
  math_expressions: ^2.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  assets:
    - assets/images/splash image.png
  uses-material-design: true
